# Generated by Django 4.2.5 on 2023-10-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_usuario_apellido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
