# Generated by Django 4.2.5 on 2023-10-25 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
