# Generated by Django 4.2.5 on 2023-10-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_usuario_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.IntegerField(default=1),
        ),
    ]
