# Generated by Django 4.2.5 on 2023-10-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(max_length=128),
        ),
    ]
